[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "fake_lesion_mask"
version = "0.1.0"
authors = [
    {name = "Vicent Caselles-Ballester", email = "vcasellesb@uoc.edu"},
    {name = "Ferran Prados"}
]
dependencies = [
   "numpy",
   "scipy",
   "nibabel"
]

[project.scripts]
fake_lesion_mask = "fake_lesion_mask.__main__:cli_main"